1.0.1: Guard check for misconfiguration or misuse
Because cryptic error "NoMethodError: undefined method 'stream_from' for nil:NilClass" isn't helpful for you, folks.